
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMINUSleftPOWERASSIGN EQ GT IDENTIFIER LBRACKET LPAREN LT MINUS NEQ NUMBER POWER QUESTION RBRACKET RPAREN SEMICOLON\nprogram : statements\n\nstatements : statement\n           | statements statement\n\nstatement : if_statement SEMICOLON\n\nif_statement : condition QUESTION assign_statement\n\nif_statement : condition QUESTION if_statement\n\nassign_statement : ASSIGN variable expression\n\ncondition : expression EQ expression\n          | expression NEQ expression\n          | expression LT expression\n          | expression GT expression\n\nexpression : expression MINUS expression\n\nexpression : expression POWER\n\nexpression : LPAREN expression RPAREN\n\nexpression : NUMBER\n\nexpression : variable\n\nvariable : IDENTIFIER\n\nvariable : IDENTIFIER LBRACKET NUMBER RBRACKET\n'

_lr_action_items = {'LPAREN':([0,2,3,7,10,11,12,13,14,15,16,17,18,32,33,],[7,7,-2,7,-17,-3,-4,7,7,7,7,7,7,7,-18,]),'NUMBER':([0,2,3,7,10,11,12,13,14,15,16,17,18,21,32,33,],[8,8,-2,8,-17,-3,-4,8,8,8,8,8,8,31,8,-18,]),'IDENTIFIER':([0,2,3,7,10,11,12,13,14,15,16,17,18,24,32,33,],[10,10,-2,10,-17,-3,-4,10,10,10,10,10,10,10,10,-18,]),'$end':([1,2,3,11,12,],[0,-1,-2,-3,-4,]),'SEMICOLON':([4,8,9,10,19,22,23,29,30,33,34,],[12,-15,-16,-17,-13,-5,-6,-12,-14,-18,-7,]),'QUESTION':([5,8,9,10,19,25,26,27,28,29,30,33,],[13,-15,-16,-17,-13,-8,-9,-10,-11,-12,-14,-18,]),'EQ':([6,8,9,10,19,29,30,33,],[14,-15,-16,-17,-13,-12,-14,-18,]),'NEQ':([6,8,9,10,19,29,30,33,],[15,-15,-16,-17,-13,-12,-14,-18,]),'LT':([6,8,9,10,19,29,30,33,],[16,-15,-16,-17,-13,-12,-14,-18,]),'GT':([6,8,9,10,19,29,30,33,],[17,-15,-16,-17,-13,-12,-14,-18,]),'MINUS':([6,8,9,10,19,20,25,26,27,28,29,30,33,34,],[18,-15,-16,-17,-13,18,18,18,18,18,-12,-14,-18,18,]),'POWER':([6,8,9,10,19,20,25,26,27,28,29,30,33,34,],[19,-15,-16,-17,-13,19,19,19,19,19,19,-14,-18,19,]),'RPAREN':([8,9,10,19,20,29,30,33,],[-15,-16,-17,-13,30,-12,-14,-18,]),'LBRACKET':([10,],[21,]),'ASSIGN':([13,],[24,]),'RBRACKET':([31,],[33,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,11,]),'if_statement':([0,2,13,],[4,4,23,]),'condition':([0,2,13,],[5,5,5,]),'expression':([0,2,7,13,14,15,16,17,18,32,],[6,6,20,6,25,26,27,28,29,34,]),'variable':([0,2,7,13,14,15,16,17,18,24,32,],[9,9,9,9,9,9,9,9,9,32,9,]),'assign_statement':([13,],[22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','main.py',159),
  ('statements -> statement','statements',1,'p_statements','main.py',167),
  ('statements -> statements statement','statements',2,'p_statements','main.py',168),
  ('statement -> if_statement SEMICOLON','statement',2,'p_statement','main.py',180),
  ('if_statement -> condition QUESTION assign_statement','if_statement',3,'p_if_statement_assign','main.py',191),
  ('if_statement -> condition QUESTION if_statement','if_statement',3,'p_if_statement_nested','main.py',199),
  ('assign_statement -> ASSIGN variable expression','assign_statement',3,'p_assign_statement','main.py',210),
  ('condition -> expression EQ expression','condition',3,'p_condition','main.py',220),
  ('condition -> expression NEQ expression','condition',3,'p_condition','main.py',221),
  ('condition -> expression LT expression','condition',3,'p_condition','main.py',222),
  ('condition -> expression GT expression','condition',3,'p_condition','main.py',223),
  ('expression -> expression MINUS expression','expression',3,'p_expression_minus','main.py',234),
  ('expression -> expression POWER','expression',2,'p_expression_square','main.py',246),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','main.py',254),
  ('expression -> NUMBER','expression',1,'p_expression_number','main.py',262),
  ('expression -> variable','expression',1,'p_expression_variable','main.py',270),
  ('variable -> IDENTIFIER','variable',1,'p_variable_simple','main.py',280),
  ('variable -> IDENTIFIER LBRACKET NUMBER RBRACKET','variable',4,'p_variable_indexed','main.py',288),
]
